{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google_mlkit_commons",
    "module": "google_mlkit_commons_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_release-1.0.aar",
          "url": "google_mlkit_commons_release-1.0.aar",
          "size": 9679,
          "sha512": "e1a9ee73d05744ef36609edafbb1baa7f11d5d99b88552d46fd29c524051d031be1da6e1a22e8271551c4a1125a0f3ea5ce699d3dc1cdabb5dc81b9eaa609297",
          "sha256": "cdea5b4957e57f3b02ae342c03bcbeec979a3e13cffa743a8266e1fbf991a5da",
          "sha1": "6e58339e181460ce977485e0e6c2b11781113450",
          "md5": "af63313a5dd42ac0328cda14acfbe2f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_release-1.0.aar",
          "url": "google_mlkit_commons_release-1.0.aar",
          "size": 9679,
          "sha512": "e1a9ee73d05744ef36609edafbb1baa7f11d5d99b88552d46fd29c524051d031be1da6e1a22e8271551c4a1125a0f3ea5ce699d3dc1cdabb5dc81b9eaa609297",
          "sha256": "cdea5b4957e57f3b02ae342c03bcbeec979a3e13cffa743a8266e1fbf991a5da",
          "sha1": "6e58339e181460ce977485e0e6c2b11781113450",
          "md5": "af63313a5dd42ac0328cda14acfbe2f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_release-1.0-sources.jar",
          "url": "google_mlkit_commons_release-1.0-sources.jar",
          "size": 3512,
          "sha512": "f732ba0c6e1966cdb6610fe60340c69e1c5fe4afac3500902bd298b99e034a434f6d7cdbd2a1b73debef9194324ff21a3be6e3930c80907d087aae237125d2aa",
          "sha256": "78fa43e90ffd11b485ccd088cbfb8cf6916bea162c351426930e7fb6e9a20609",
          "sha1": "6f31bf0d8540f58dbec893db45063f9e96961463",
          "md5": "54bd5f01284a093ebad74cf42c2606be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_release-1.0-javadoc.jar",
          "url": "google_mlkit_commons_release-1.0-javadoc.jar",
          "size": 277107,
          "sha512": "145d2fac259e461c558f4e6baae4b362be8ac39a757bb523221003a4f5ca994756e51202cd85e761acc3e818b687bf4c80b9061e84763bd45d05feefd752a95e",
          "sha256": "093b50f49718ea5b25ea228dcb479993aa34655ee21ae8f80de98442411f0959",
          "sha1": "66a1c08dfa70016e75810a0b87a74be440f13321",
          "md5": "0aa68918f37e826a9a493991602b22ed"
        }
      ]
    }
  ]
}
