{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-1.0.aar",
          "url": "camera_android_debug-1.0.aar",
          "size": 170381,
          "sha512": "80d3771e27fe9c928e5be5b4cc10db0fe3c3a736ed94e58d67fece453ff0477261cf59b63df93772e9f35e4ba71b7d56032240944879fb97b4647a9aa2679585",
          "sha256": "66d7d09f9aafd82e7ec7257af4c8684ad39e8c351b5816b046e7753a4fe2d031",
          "sha1": "b6a660175b552b37ef52df77796ddc797fc70518",
          "md5": "155faae5060f08c3f6050d04db7f0686"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-1.0.aar",
          "url": "camera_android_debug-1.0.aar",
          "size": 170381,
          "sha512": "80d3771e27fe9c928e5be5b4cc10db0fe3c3a736ed94e58d67fece453ff0477261cf59b63df93772e9f35e4ba71b7d56032240944879fb97b4647a9aa2679585",
          "sha256": "66d7d09f9aafd82e7ec7257af4c8684ad39e8c351b5816b046e7753a4fe2d031",
          "sha1": "b6a660175b552b37ef52df77796ddc797fc70518",
          "md5": "155faae5060f08c3f6050d04db7f0686"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_debug-1.0-sources.jar",
          "url": "camera_android_debug-1.0-sources.jar",
          "size": 87503,
          "sha512": "3b42096e0f0138e8d32071c08851ee3b72c149fdf6ba37fad01b34270767c4a113e6e50bb3a0027aee55ace9fbb6a0b783ddfdbdcad099632ecc65e0c247cb1e",
          "sha256": "331d6a3ec468860c438fa72d7f79aedbc4246652c36ac046ee0b50313924b398",
          "sha1": "6d38db09f8b2c9b47238704b9eb16d96b787266d",
          "md5": "7c43aa5552d84594caff38c504e71ed4"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_debug-1.0-javadoc.jar",
          "url": "camera_android_debug-1.0-javadoc.jar",
          "size": 603531,
          "sha512": "3de02a6af2786f688b1a8b89deebf00443e6449fb138e0b34f89bc797f0e91927ab3ea609ced2bf64de0c7714c5f4ebabd50b17b37a0cb60163a8ac561155325",
          "sha256": "1d934868a8fbf21daee4468f74eb0f1c685d53f37d1bb78625501ac912609163",
          "sha1": "99198499726ad93bbd37da665ccde72858c3c171",
          "md5": "ee6d0753a4e2a4d825837198f38ca16e"
        }
      ]
    }
  ]
}
