{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "native_image_cropper_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "native_image_cropper_android_debug-1.0.aar",
          "url": "native_image_cropper_android_debug-1.0.aar",
          "size": 10488,
          "sha512": "ce37fce149dded02ad68929773960131a51cb57674332df3f4f4ace69bb185681463214a83b1610d467088a77b6301c38857183b603746abe2cbf3cd31b2a91e",
          "sha256": "9230f70b444a8308e0272b36b55482c2d1a7ab606a3f0c77015e8b09b45e38f0",
          "sha1": "204d1aa186eb07ff966a8bcdf97fbd115e2471d5",
          "md5": "f72431d86e07cef23400ded35a0d097f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "native_image_cropper_android_debug-1.0.aar",
          "url": "native_image_cropper_android_debug-1.0.aar",
          "size": 10488,
          "sha512": "ce37fce149dded02ad68929773960131a51cb57674332df3f4f4ace69bb185681463214a83b1610d467088a77b6301c38857183b603746abe2cbf3cd31b2a91e",
          "sha256": "9230f70b444a8308e0272b36b55482c2d1a7ab606a3f0c77015e8b09b45e38f0",
          "sha1": "204d1aa186eb07ff966a8bcdf97fbd115e2471d5",
          "md5": "f72431d86e07cef23400ded35a0d097f"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native_image_cropper_android_debug-1.0-sources.jar",
          "url": "native_image_cropper_android_debug-1.0-sources.jar",
          "size": 3388,
          "sha512": "695ea0a89fa8fd9d00296a1b9e74c72622590efbadefe511468e3f6e0b5a0ec865fe000be68404aaa1b1e7330160ecee5690b963e8aa532b6d1f29ceea440ebc",
          "sha256": "02cd3a9c1bceb14669e3c588f226447c2d6f34dce8e5afc1f762836dd6e01507",
          "sha1": "43457c7247b2527ba2b1e4b2842d03b738a4fca4",
          "md5": "75bf3ad290e63b266b006207698b7c40"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native_image_cropper_android_debug-1.0-javadoc.jar",
          "url": "native_image_cropper_android_debug-1.0-javadoc.jar",
          "size": 269495,
          "sha512": "be934a9a1c3a8122386fd0147fce54829e30ca883e993b5ef4da94b4e1b65ee05a7323234a06a99258ab26a9498d504b6179da5d4c1d486b2e14ead0662d1f1a",
          "sha256": "76838a7f33ef6bd03b5f3feb27aef7a2e6ca2e59f13cff2626f5453b30fe30a5",
          "sha1": "4893ffefae8d98ff7281fc29a2a44fbf7eaec00e",
          "md5": "97514949f6dc82a0991e8b74191259f9"
        }
      ]
    }
  ]
}
