{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-1.0.aar",
          "url": "camera_android_profile-1.0.aar",
          "size": 161306,
          "sha512": "fe61aad4e3f8131cac0f1473500a0bfe57f9e4b4dd0e72b03b61eb6fca911983be7391394af0078bd2f8673912a0008c7f4fd33409de24148fc02fc1bdf0d8fe",
          "sha256": "254dc043876baff49b168e56de2472ace15f8060613768dc252d3e88fbedec68",
          "sha1": "2e539139bbce6a158c80a7cba1df415f0de01bc8",
          "md5": "39a19d4d090e8156e820c1f3c9c5b8e9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-1.0.aar",
          "url": "camera_android_profile-1.0.aar",
          "size": 161306,
          "sha512": "fe61aad4e3f8131cac0f1473500a0bfe57f9e4b4dd0e72b03b61eb6fca911983be7391394af0078bd2f8673912a0008c7f4fd33409de24148fc02fc1bdf0d8fe",
          "sha256": "254dc043876baff49b168e56de2472ace15f8060613768dc252d3e88fbedec68",
          "sha1": "2e539139bbce6a158c80a7cba1df415f0de01bc8",
          "md5": "39a19d4d090e8156e820c1f3c9c5b8e9"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_profile-1.0-sources.jar",
          "url": "camera_android_profile-1.0-sources.jar",
          "size": 87491,
          "sha512": "22bdaddb09fa5a226bc719aff5d3d7dcdb67cc81d22a35044e77941810df75033b1d3961b4fd977c3afb86c87e6a3080c6a6e0ddd54e192da4aa021018a1559a",
          "sha256": "5df2d6437f322de05f579945c0f963abe7b2557dd1d39f252573b694c7741d92",
          "sha1": "0276048a9ae9d83ab47624952565e5f3e5368f69",
          "md5": "c252a2ef4e460457ffeef3eed26aedaf"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_profile-1.0-javadoc.jar",
          "url": "camera_android_profile-1.0-javadoc.jar",
          "size": 603531,
          "sha512": "08375f093ee06afa8f56455caa94e49149f64b8429379962acbd32eaa4a356305c2ba102d12c8ea7a41c4ec71800056fd11f5db4c521c28b2c917bf60dcedfc5",
          "sha256": "0833c0c239fd0e35dfc1615059cec6f29219fc5143dbbe0e95c518a2621ab59d",
          "sha1": "f270797faf7259fb915831a30ecff86ac925d43e",
          "md5": "39551ff2287470da49f6a5eb6ad1cf8c"
        }
      ]
    }
  ]
}
