{
  "formatVersion": "1.1",
  "component": {
    "group": "android_generated",
    "module": "native_image_cropper_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "native_image_cropper_android_profile-1.0.aar",
          "url": "native_image_cropper_android_profile-1.0.aar",
          "size": 10138,
          "sha512": "e2a23ddd87590ad98da12b6398bcd89764d6511eb25ea8a303038e0aaa40724d238913d6d7da893645e3092c594c4bcddf5ac5680c6379b4ec739e5dd6ef2eb5",
          "sha256": "0dc5c5d83f5eae759b20652773f94e70a247d28259af753541be95620c734dc7",
          "sha1": "a9f6d9fbec7ad1da03646da00c28460bfcda3123",
          "md5": "2c86282ab197db9e0561e5572dbe729f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "native_image_cropper_android_profile-1.0.aar",
          "url": "native_image_cropper_android_profile-1.0.aar",
          "size": 10138,
          "sha512": "e2a23ddd87590ad98da12b6398bcd89764d6511eb25ea8a303038e0aaa40724d238913d6d7da893645e3092c594c4bcddf5ac5680c6379b4ec739e5dd6ef2eb5",
          "sha256": "0dc5c5d83f5eae759b20652773f94e70a247d28259af753541be95620c734dc7",
          "sha1": "a9f6d9fbec7ad1da03646da00c28460bfcda3123",
          "md5": "2c86282ab197db9e0561e5572dbe729f"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native_image_cropper_android_profile-1.0-sources.jar",
          "url": "native_image_cropper_android_profile-1.0-sources.jar",
          "size": 3375,
          "sha512": "0795bebd949a02238bc45cfeac43eeada23ea2c5bcb9ca7161f48a6fbefd740ff4e192f5576c2aba620218af1caf16ad95bc4f88f63e7ee8610a6773246e5c8b",
          "sha256": "48a123460081fc7bed646690e717db08700668f99d1dc35c3b522a864e08e1e7",
          "sha1": "8760a8a8d6b400e7b1cbaf903e77d5b28f9b25f8",
          "md5": "621e2f98095736adb3db1805f40f07b7"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native_image_cropper_android_profile-1.0-javadoc.jar",
          "url": "native_image_cropper_android_profile-1.0-javadoc.jar",
          "size": 269495,
          "sha512": "be934a9a1c3a8122386fd0147fce54829e30ca883e993b5ef4da94b4e1b65ee05a7323234a06a99258ab26a9498d504b6179da5d4c1d486b2e14ead0662d1f1a",
          "sha256": "76838a7f33ef6bd03b5f3feb27aef7a2e6ca2e59f13cff2626f5453b30fe30a5",
          "sha1": "4893ffefae8d98ff7281fc29a2a44fbf7eaec00e",
          "md5": "97514949f6dc82a0991e8b74191259f9"
        }
      ]
    }
  ]
}
