{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 120243,
          "sha512": "6480fe213bac8d2ad8be1e7d7fdece82ecef18471630ff03950b30514dccee677390bb1eae78eccc55220381b4d30db5cfb5ea52b9a7970d5fa661dc43c7eb8a",
          "sha256": "e5b84c433eeb3a9f03ec0d3b7301278d82afb67f0b74044ed47c3799981414ac",
          "sha1": "a55448ac4d18db0c8728e66d637695cd51012c68",
          "md5": "9304dac6c4f42ac2f36ca74c556d31f5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 120243,
          "sha512": "6480fe213bac8d2ad8be1e7d7fdece82ecef18471630ff03950b30514dccee677390bb1eae78eccc55220381b4d30db5cfb5ea52b9a7970d5fa661dc43c7eb8a",
          "sha256": "e5b84c433eeb3a9f03ec0d3b7301278d82afb67f0b74044ed47c3799981414ac",
          "sha1": "a55448ac4d18db0c8728e66d637695cd51012c68",
          "md5": "9304dac6c4f42ac2f36ca74c556d31f5"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0-sources.jar",
          "url": "shared_preferences_android_debug-1.0-sources.jar",
          "size": 12260,
          "sha512": "3d54815916935e739ee5fbb9f9b3fccebce6550fe8bb1f2c24d78c3fe290868ccc9b4967f014999f529659e1ff38f6e5cc7351eb6f643f3619bc924d4d2444e2",
          "sha256": "ba2be8dce39dea0200ba9121a1c5c594c3c47d98b26b31a0451d120170e67bb1",
          "sha1": "57d2eb51cc654d4fb3ad936e822bceadcbef8efc",
          "md5": "dbbe103b3e51a60c0c250ce794021689"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0-javadoc.jar",
          "url": "shared_preferences_android_debug-1.0-javadoc.jar",
          "size": 340265,
          "sha512": "a2476bdf3b772bed152f6b955b76daffc837a45d448b2cd086000ace07710d31923561ebd26a6dc83421285d61864dddfbb643c74dba71e6d2a5708c2dcae690",
          "sha256": "84a8aa2dd0408740bf945bbd59ab1220b3cceaddd18064362cf2f4d7c7b79547",
          "sha1": "15c81407c1d6202800fc930acb186dc911652f2d",
          "md5": "baae6370b7f022bf9ea88277f11a4dda"
        }
      ]
    }
  ]
}
