{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-1.0.aar",
          "url": "camera_android_profile-1.0.aar",
          "size": 161306,
          "sha512": "fe61aad4e3f8131cac0f1473500a0bfe57f9e4b4dd0e72b03b61eb6fca911983be7391394af0078bd2f8673912a0008c7f4fd33409de24148fc02fc1bdf0d8fe",
          "sha256": "254dc043876baff49b168e56de2472ace15f8060613768dc252d3e88fbedec68",
          "sha1": "2e539139bbce6a158c80a7cba1df415f0de01bc8",
          "md5": "39a19d4d090e8156e820c1f3c9c5b8e9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-1.0.aar",
          "url": "camera_android_profile-1.0.aar",
          "size": 161306,
          "sha512": "fe61aad4e3f8131cac0f1473500a0bfe57f9e4b4dd0e72b03b61eb6fca911983be7391394af0078bd2f8673912a0008c7f4fd33409de24148fc02fc1bdf0d8fe",
          "sha256": "254dc043876baff49b168e56de2472ace15f8060613768dc252d3e88fbedec68",
          "sha1": "2e539139bbce6a158c80a7cba1df415f0de01bc8",
          "md5": "39a19d4d090e8156e820c1f3c9c5b8e9"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_profile-1.0-sources.jar",
          "url": "camera_android_profile-1.0-sources.jar",
          "size": 87491,
          "sha512": "22bdaddb09fa5a226bc719aff5d3d7dcdb67cc81d22a35044e77941810df75033b1d3961b4fd977c3afb86c87e6a3080c6a6e0ddd54e192da4aa021018a1559a",
          "sha256": "5df2d6437f322de05f579945c0f963abe7b2557dd1d39f252573b694c7741d92",
          "sha1": "0276048a9ae9d83ab47624952565e5f3e5368f69",
          "md5": "c252a2ef4e460457ffeef3eed26aedaf"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_profile-1.0-javadoc.jar",
          "url": "camera_android_profile-1.0-javadoc.jar",
          "size": 603574,
          "sha512": "18ebb5372ea9559577213e4d2104db9d4b9afba1023d4e69ebd7bbc9e9670b6120a9b7be39ca69e0271a017b7f05724bbf717e3cd4aa9bc05e5ad1e3d35ed567",
          "sha256": "51b5327bc6da21891033aff4471dadcbba6eb20aaebaedbdd27b023152d234a7",
          "sha1": "4bfacfaa7b5721f24e7666b0e59376a88474ac05",
          "md5": "3ec1bf390b867eb26aa7546987187f6b"
        }
      ]
    }
  ]
}
