{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 72818,
          "sha512": "0893dafca28c0a6ad4e36b4accf818af7564682101d64817ae31edef86350003e64fbc80c4f996c960555b9dc3672290195d50dea8b5b72f964a2f9e52304cbd",
          "sha256": "f4d5edcc706ba14fb9b48f91fd674ce926b8759ab4d7917963c958dffc5fde4f",
          "sha1": "cfabd48410840499f3f5570a30a3a0ca650db351",
          "md5": "fb92b7abac7c06aa1adeb0fd5988f9f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 72818,
          "sha512": "0893dafca28c0a6ad4e36b4accf818af7564682101d64817ae31edef86350003e64fbc80c4f996c960555b9dc3672290195d50dea8b5b72f964a2f9e52304cbd",
          "sha256": "f4d5edcc706ba14fb9b48f91fd674ce926b8759ab4d7917963c958dffc5fde4f",
          "sha1": "cfabd48410840499f3f5570a30a3a0ca650db351",
          "md5": "fb92b7abac7c06aa1adeb0fd5988f9f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-sources.jar",
          "url": "image_picker_android_release-1.0-sources.jar",
          "size": 27085,
          "sha512": "9b1a2d931deaf541f664cac9583b23e2823e55e64e213943ac0f3eefc0ce7cd339700f45126d73022e5b74f484b45a1de3b9b7d6f007b56033f25ee57edba5ec",
          "sha256": "d5807e51a85653592dc5025eb127daa35fe091e758f030bd52c97f8584367fa0",
          "sha1": "9e603cd975d7f9a35dad6d3a98e2071080eda7cc",
          "md5": "9c20a3e3ca7c28055fea05a4f6b1a57b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-javadoc.jar",
          "url": "image_picker_android_release-1.0-javadoc.jar",
          "size": 385251,
          "sha512": "305483b464f17d82ed8a5144f011d4cd0186e3a645bc61125de59c5bf64d28d7efe8e09ad87a4cad74fbe5bf8a7eda34d654786fa153eb95a78bc9d5c9ea38e0",
          "sha256": "b1ba297b49917b6a28a2e144e396cc54bffc072221d3ccf6206cf86bc06555eb",
          "sha1": "265fc76f2c16e7321853056c2c56c166e31d9cb6",
          "md5": "fc730dfaa2e96e58682ddf2475bf7fcf"
        }
      ]
    }
  ]
}
