{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 72822,
          "sha512": "3d6f4f6edf9ea1dee1bc15302aed08e69bd818e43b3e5062e5475254e4f9ff6cc01fb2cbc3f971225269827f1b547bbfc14c5518d86306b32c75323de1a15ea8",
          "sha256": "e6e85df82688775bf73a821e2829ff0cf1758647b8ac2b109b3f8945811237bb",
          "sha1": "cd7bf09e33353b664102b0593db6685630669d30",
          "md5": "541dd6698e18e2132c1de61b5c592cff"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 72822,
          "sha512": "3d6f4f6edf9ea1dee1bc15302aed08e69bd818e43b3e5062e5475254e4f9ff6cc01fb2cbc3f971225269827f1b547bbfc14c5518d86306b32c75323de1a15ea8",
          "sha256": "e6e85df82688775bf73a821e2829ff0cf1758647b8ac2b109b3f8945811237bb",
          "sha1": "cd7bf09e33353b664102b0593db6685630669d30",
          "md5": "541dd6698e18e2132c1de61b5c592cff"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_profile-1.0-sources.jar",
          "url": "image_picker_android_profile-1.0-sources.jar",
          "size": 27087,
          "sha512": "6316635a3a5df0dee6176cf57e976d313855d4d2648d8e4e41fc84f681e2c75c92828dd2fd6455f88485df4dda379cc497ed465117409c643ddd203cff01835f",
          "sha256": "e460c69cfa807c3f0ae7dcbf8fafe487738f78d6e2f35e5aa41a0b96b08136bf",
          "sha1": "86232968074739b8acf7d0d57814e663e4e58ae1",
          "md5": "0609b1157164eab801175ad03da13ff7"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_profile-1.0-javadoc.jar",
          "url": "image_picker_android_profile-1.0-javadoc.jar",
          "size": 385251,
          "sha512": "305483b464f17d82ed8a5144f011d4cd0186e3a645bc61125de59c5bf64d28d7efe8e09ad87a4cad74fbe5bf8a7eda34d654786fa153eb95a78bc9d5c9ea38e0",
          "sha256": "b1ba297b49917b6a28a2e144e396cc54bffc072221d3ccf6206cf86bc06555eb",
          "sha1": "265fc76f2c16e7321853056c2c56c166e31d9cb6",
          "md5": "fc730dfaa2e96e58682ddf2475bf7fcf"
        }
      ]
    }
  ]
}
