{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 23190,
          "sha512": "bd90398eb822e255d47dee34bb0c3f054a894818facd448a166d064089b773fecbf1046c76cca55a443bb6900f33416e7ca8553dd122b1530e02d8e8cdeea4a4",
          "sha256": "cda2185c0e46f121758db161815e4bb2caf7ceb0b695e02dcfa3dc71fe4d034c",
          "sha1": "5f8fd055d16573a5c14d10796734a89897407b36",
          "md5": "aa687ca8603b21e1c1ec07ae149ec04d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 23190,
          "sha512": "bd90398eb822e255d47dee34bb0c3f054a894818facd448a166d064089b773fecbf1046c76cca55a443bb6900f33416e7ca8553dd122b1530e02d8e8cdeea4a4",
          "sha256": "cda2185c0e46f121758db161815e4bb2caf7ceb0b695e02dcfa3dc71fe4d034c",
          "sha1": "5f8fd055d16573a5c14d10796734a89897407b36",
          "md5": "aa687ca8603b21e1c1ec07ae149ec04d"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_profile-1.0-sources.jar",
          "url": "share_plus_profile-1.0-sources.jar",
          "size": 7964,
          "sha512": "aa7e8269428d6aaeb05472d3bcc96320e795778afe41d3f4945dce5daef7868aeb6cc6c30e472635b68da15cd4cb3384e51d94c1047b1798370bfaf23b4fcd7d",
          "sha256": "bc94341f3905a4bf39c360a8ea99ebc604135de401a561be1cbc0f25ebaa95fe",
          "sha1": "8c3e287830b18e8ac36cb9d1df4ac0d4b49274ed",
          "md5": "2b55b05de2d9d8a5c1fdd09a890526a9"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_profile-1.0-javadoc.jar",
          "url": "share_plus_profile-1.0-javadoc.jar",
          "size": 286171,
          "sha512": "53e1466955554831a729b7cb26c0f7bf099a453a1403133d8d968a66638a81bc63d5decb32c1255b7ab378a2c9c3985c8a965c09b9e0ee41933ae3540a162441",
          "sha256": "6684a14b488b2ac77d57954bbeed6a96b8379c073e858d5d04f31380c98936d6",
          "sha1": "e6a783868e1e8579f1786d3bbdde751e6a33ef5a",
          "md5": "ab0220612cba548828550dec308021ea"
        }
      ]
    }
  ]
}
